
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrtmoooreqktqrcitwsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZydG1vb29yZXFrdHFyY2l0d3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzc3NzYsImV4cCI6MjA1ODkxMzc3Nn0.gFCdSDIdFLJ3kTMBmNFcTYP6RzVAlFHD2C6XyOq5t1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
